SET search_path TO bip_pim_015;
WITH visible_profiles AS (SELECT p.user_id FROM profiles p JOIN users u ON u.user_id=p.user_id AND u.status='active' LEFT JOIN friendships fr ON fr.user_id_low=LEAST(1,p.user_id) AND fr.user_id_high=GREATEST(1,p.user_id) AND fr.state='accepted' LEFT JOIN block_edges b ON b.blocker_user_id=p.user_id AND b.blocked_user_id=1 WHERE p.user_id<>1 AND b.blocker_user_id IS NULL AND (p.visibility='public' OR (p.visibility='friends_only' AND fr.user_id_low IS NOT NULL))), visible_posts AS (SELECT p.post_id FROM posts p JOIN users a ON a.user_id=p.author_user_id AND a.status='active' LEFT JOIN audience_group_members agm ON agm.group_id=p.audience_group_id AND agm.member_user_id=1 LEFT JOIN block_edges b ON b.blocker_user_id=p.author_user_id AND b.blocked_user_id=1 WHERE p.deleted_at IS NULL AND b.blocker_user_id IS NULL AND (p.visibility='public' OR (p.visibility='close_friends' AND agm.group_id IS NOT NULL))), controlled_feed AS (SELECT vp.post_id FROM visible_posts vp JOIN posts p ON p.post_id=vp.post_id LEFT JOIN hide_events h ON h.viewer_user_id=1 AND h.post_id=vp.post_id LEFT JOIN mute_edges m ON m.muter_user_id=1 AND m.muted_user_id=p.author_user_id AND m.state='active' WHERE h.event_id IS NULL AND m.muter_user_id IS NULL), share_save AS (SELECT (SELECT count(*) FROM reposts r JOIN posts p ON p.post_id=r.original_post_id WHERE r.deleted_at IS NULL AND p.deleted_at IS NULL)::text AS visible_reposts, (SELECT count(*) FROM bookmarks WHERE user_id=1 AND deleted_at IS NULL)::text AS own_saves), source_counts AS (SELECT p.post_id, count(DISTINCT pr.reaction_id) FILTER (WHERE pr.deleted_at IS NULL) AS likes, count(DISTINCT c.comment_id) FILTER (WHERE c.deleted_at IS NULL) AS comments FROM posts p LEFT JOIN post_reactions pr ON pr.post_id=p.post_id LEFT JOIN comments c ON c.post_id=p.post_id GROUP BY p.post_id), follower_source AS (SELECT followed_user_id AS user_id, count(*) AS followers FROM friendships, LATERAL (SELECT user_id_low AS follower_user_id, user_id_high AS followed_user_id UNION ALL SELECT user_id_high, user_id_low) f WHERE state='accepted' GROUP BY followed_user_id), drift AS (SELECT 'post_like' AS drift_type, sc.post_id::text AS subject_id, (sc.likes-rm.like_count)::text AS delta FROM source_counts sc JOIN post_count_read_models rm ON rm.post_id=sc.post_id WHERE sc.likes<>rm.like_count UNION ALL SELECT 'follower', fs.user_id::text, (fs.followers-rm.follower_count)::text FROM follower_source fs JOIN user_count_read_models rm ON rm.user_id=fs.user_id WHERE fs.followers<>rm.follower_count), checks AS (
  SELECT 'profile_visibility_contract' contract_name, 'viewer:1' subject_id, COALESCE(string_agg(user_id::text,'|' ORDER BY user_id),'none') observed_value, 'Ada sees Ben and Cy profiles but not blocked Omar' expected_reason FROM visible_profiles
  UNION ALL SELECT 'post_visibility_contract','viewer:1',COALESCE(string_agg(post_id::text,'|' ORDER BY post_id),'none'),'Visible posts honor public close-friends block and deleted rules' FROM visible_posts
  UNION ALL SELECT 'user_controls_contract','viewer:1',COALESCE(string_agg(post_id::text,'|' ORDER BY post_id),'none'),'Controlled feed removes hidden Ben post 503 and muted Eli post 504' FROM controlled_feed
  UNION ALL SELECT 'share_save_contract','viewer:1',visible_reposts||' reposts/'||own_saves||' saves','Share/save contract separates repost lifecycle and private saves' FROM share_save
  UNION ALL SELECT 'post_counts_contract','post:501',likes::text||' likes/'||comments::text||' comments','Source post counts ignore deleted reaction and comment rows' FROM source_counts WHERE post_id=501
  UNION ALL SELECT 'follower_counts_contract','user:2',followers::text,'Source follower count for Ben derives from accepted friendships' FROM follower_source WHERE user_id=2
  UNION ALL SELECT 'unread_counts_contract','user:1',count(*)::text,'Unread notification count excludes read notification 1303' FROM notifications WHERE recipient_user_id=1 AND state='unread'
  UNION ALL SELECT 'drift_contract','all',COALESCE(string_agg(drift_type||':'||subject_id||':'||delta,'|' ORDER BY drift_type, subject_id),'none'),'Drift compares source counts with read-model counters' FROM drift
  UNION ALL SELECT 'repair_candidate_contract','all',COALESCE(string_agg(drift_type||':'||subject_id,'|' ORDER BY drift_type, subject_id),'none'),'Repair candidates are rows with drift' FROM drift
)
SELECT contract_name, subject_id, observed_value, expected_reason FROM checks ORDER BY contract_name;
