SET search_path TO bip_pim_034;
WITH active_members AS (SELECT * FROM community_memberships WHERE member_state='active'), eligible_rsvps AS (SELECT r.* FROM event_rsvps r JOIN community_events e USING(event_id) WHERE NOT e.member_only OR EXISTS(SELECT 1 FROM active_members m WHERE m.community_id=e.community_id AND m.user_id=r.user_id)), going_counts AS (SELECT event_id,count(*) going_count FROM eligible_rsvps WHERE rsvp_state='going' GROUP BY event_id), upcoming_events AS (SELECT * FROM community_events WHERE event_state='scheduled'), valid_attendance AS (SELECT a.* FROM event_attendance a JOIN event_rsvps r ON r.rsvp_id=a.rsvp_id AND r.rsvp_state='going' AND r.user_id=a.user_id AND r.event_id=a.event_id), checks AS (
SELECT 'member_rsvp_allowed' contract_name,'rsvp:3001' subject_id,(EXISTS(SELECT 1 FROM eligible_rsvps WHERE rsvp_id=3001))::text observed_value,'Ada active membership 1001 can RSVP going to member-only event 2001' expected_reason
UNION ALL SELECT 'non_member_rsvp_denied','rsvp:3003',(NOT EXISTS(SELECT 1 FROM eligible_rsvps WHERE rsvp_id=3003))::text,'Cy has no membership row and cannot RSVP to private community event'
UNION ALL SELECT 'declined_not_counted','rsvp:3004',(NOT EXISTS(SELECT 1 FROM eligible_rsvps WHERE rsvp_id=3004 AND rsvp_state='going'))::text,'Diya declined RSVP 3004 does not count toward capacity'
UNION ALL SELECT 'waitlisted_not_going','rsvp:3005',(NOT EXISTS(SELECT 1 FROM eligible_rsvps WHERE rsvp_id=3005 AND rsvp_state='going'))::text,'Eli waitlisted RSVP 3005 is not a going seat until promoted'
UNION ALL SELECT 'cancelled_event_hidden','event:2002',(NOT EXISTS(SELECT 1 FROM upcoming_events WHERE event_id=2002))::text,'Cancelled event 2002 is suppressed from upcoming list'
UNION ALL SELECT 'attendance_checkin_contract','attendance:5001',(EXISTS(SELECT 1 FROM valid_attendance WHERE attendance_id=5001))::text,'Attendance 5001 links to Ada going RSVP 3001'
UNION ALL SELECT 'waitlist_promotion_contract','event:2001',string_agg(user_id||':'||waitlist_state,'|' ORDER BY waitlist_rank),'Waitlist row 4005 records promotion lifecycle separately from RSVP' FROM event_waitlist WHERE event_id=2001
UNION ALL SELECT 'event_lifecycle_trace','event:2001','going='||COALESCE((SELECT going_count::text FROM going_counts WHERE event_id=2001),'0')||'|capacity='||(SELECT capacity FROM community_events WHERE event_id=2001)||'|upcoming='||(EXISTS(SELECT 1 FROM upcoming_events WHERE event_id=2001))::text,'Trace combines membership, RSVP state, capacity, waitlist, attendance, and cancellation')
SELECT contract_name,subject_id,observed_value,expected_reason FROM checks ORDER BY contract_name;
