SET search_path TO bip_pim_010;
WITH visible_profiles AS (SELECT p.user_id FROM profiles p JOIN users u ON u.user_id=p.user_id AND u.status='active' LEFT JOIN follow_edges f ON f.follower_user_id=1 AND f.followed_user_id=p.user_id AND f.state='active' LEFT JOIN block_edges b1 ON b1.blocker_user_id=p.user_id AND b1.blocked_user_id=1 LEFT JOIN block_edges b2 ON b2.blocker_user_id=1 AND b2.blocked_user_id=p.user_id WHERE p.user_id<>1 AND b1.blocker_user_id IS NULL AND b2.blocker_user_id IS NULL AND (p.visibility='public' OR (p.visibility='followers' AND f.follower_user_id IS NOT NULL))), post_counts AS (SELECT p.post_id, count(DISTINCT r.reaction_id) FILTER (WHERE r.deleted_at IS NULL) AS likes, count(DISTINCT c.comment_id) FILTER (WHERE c.deleted_at IS NULL) AS comments FROM posts p LEFT JOIN post_reactions r ON r.post_id=p.post_id LEFT JOIN comments c ON c.post_id=p.post_id WHERE p.deleted_at IS NULL GROUP BY p.post_id), home_feed AS (SELECT p.post_id FROM posts p JOIN users a ON a.user_id=p.author_user_id AND a.status='active' JOIN follow_edges f ON f.followed_user_id=p.author_user_id AND f.follower_user_id=1 AND f.state='active' LEFT JOIN block_edges b ON b.blocker_user_id=p.author_user_id AND b.blocked_user_id=1 WHERE p.deleted_at IS NULL AND b.blocker_user_id IS NULL ORDER BY p.created_at DESC, p.post_id DESC), visible_activity AS (SELECT e.event_id FROM activity_events e JOIN posts p ON p.post_id=e.object_id AND p.deleted_at IS NULL JOIN users a ON a.user_id=e.actor_user_id AND a.status='active' LEFT JOIN follow_edges f ON f.follower_user_id=1 AND f.followed_user_id=e.actor_user_id AND f.state='active' LEFT JOIN block_edges b ON b.blocker_user_id=e.actor_user_id AND b.blocked_user_id=1 WHERE b.blocker_user_id IS NULL AND (e.audience='public' OR (e.audience='followers' AND f.follower_user_id IS NOT NULL))), recs AS (SELECT p.author_user_id FROM user_interests ui JOIN post_tags pt ON pt.tag=ui.tag JOIN posts p ON p.post_id=pt.post_id AND p.deleted_at IS NULL LEFT JOIN follow_edges f ON f.follower_user_id=1 AND f.followed_user_id=p.author_user_id AND f.state='active' LEFT JOIN matches m ON m.user_id_low=LEAST(1,p.author_user_id) AND m.user_id_high=GREATEST(1,p.author_user_id) AND m.unmatched_at IS NULL WHERE ui.user_id=1 AND p.author_user_id<>1 AND f.follower_user_id IS NULL AND m.match_id IS NULL), checks AS (
  SELECT 'profile_contract' contract_name, 'viewer:1' subject_id, COALESCE(string_agg(user_id::text,'|' ORDER BY user_id),'none') observed_value, 'Ada sees Ben/Diya/Eli but not Cy blocked or inactive Fay' expected_reason FROM visible_profiles
  UNION ALL SELECT 'follow_contract','Ada->Ben',count(*)::text,'Active follow edge from Ada to Ben drives profile and feed visibility' FROM follow_edges WHERE follower_user_id=1 AND followed_user_id=2 AND state='active'
  UNION ALL SELECT 'post_counts_contract','post:1001',(likes::text||' likes/'||comments::text||' comments'),'Only live reactions and comments count on Ben post 1001' FROM post_counts WHERE post_id=1001
  UNION ALL SELECT 'match_contract','Ada-Diya',count(*)::text,'Mutual right swipes produce one active Ada/Diya match' FROM matches WHERE user_id_low=1 AND user_id_high=4 AND unmatched_at IS NULL
  UNION ALL SELECT 'notification_contract','recipient:1',count(*)::text,'Ada unread notifications exclude read comment 6003' FROM notifications WHERE recipient_user_id=1 AND state='unread'
  UNION ALL SELECT 'activity_contract','viewer:1',COALESCE(string_agg(event_id::text,'|' ORDER BY event_id),'none'),'Activity hides blocked Cy and deleted Ben post 1002' FROM visible_activity
  UNION ALL SELECT 'home_feed_contract','viewer:1',COALESCE(string_agg(post_id::text,'|' ORDER BY post_id),'none'),'Home feed includes live posts from active followed authors only' FROM home_feed
  UNION ALL SELECT 'recommendation_contract','viewer:1',COALESCE(string_agg(author_user_id::text,'|' ORDER BY author_user_id),'none'),'Recommendation candidates use shared interests and exclude followed or matched users' FROM recs
)
SELECT contract_name, subject_id, observed_value, expected_reason FROM checks ORDER BY contract_name;
