SET search_path TO bip_pim_039;
WITH visible_collections AS (SELECT c.* FROM collections c WHERE c.visibility='public' OR c.owner_user_id=1 OR EXISTS(SELECT 1 FROM collection_members cm WHERE cm.collection_id=c.collection_id AND cm.user_id=1 AND cm.member_state='active')), cy_visible AS (SELECT c.* FROM collections c WHERE c.visibility='public' OR c.owner_user_id=3 OR EXISTS(SELECT 1 FROM collection_members cm WHERE cm.collection_id=c.collection_id AND cm.user_id=3 AND cm.member_state='active')), active_items AS (SELECT ci.* FROM collection_items ci WHERE ci.item_state='active'), visible_items AS (SELECT ai.* FROM active_items ai JOIN visible_collections vc USING(collection_id) WHERE NOT EXISTS(SELECT 1 FROM posts p WHERE ai.entity_type='post' AND p.post_id=ai.entity_id AND p.content_state<>'active') AND NOT EXISTS(SELECT 1 FROM listings l WHERE ai.entity_type='listing' AND l.listing_id=ai.entity_id AND l.listing_state<>'active') AND NOT EXISTS(SELECT 1 FROM posts p JOIN block_edges b ON b.blocker_user_id=1 AND b.blocked_user_id=p.author_user_id WHERE ai.entity_type='post' AND p.post_id=ai.entity_id) AND NOT EXISTS(SELECT 1 FROM listings l JOIN block_edges b ON b.blocker_user_id=1 AND b.blocked_user_id=l.seller_user_id WHERE ai.entity_type='listing' AND l.listing_id=ai.entity_id) AND NOT EXISTS(SELECT 1 FROM content_treatments t WHERE t.entity_type=ai.entity_type AND t.entity_id=ai.entity_id AND t.treatment='hide')), checks AS (
SELECT 'private_collection_owner_visible' contract_name,'collection:3001' subject_id,(EXISTS(SELECT 1 FROM visible_collections WHERE collection_id=3001))::text observed_value,'Ada owns private collection 3001' expected_reason
UNION ALL SELECT 'private_collection_non_member_hidden','collection:3001',(NOT EXISTS(SELECT 1 FROM cy_visible WHERE collection_id=3001))::text,'Cy is not owner or member of private collection 3001'
UNION ALL SELECT 'public_collection_visible','collection:3002',(EXISTS(SELECT 1 FROM cy_visible WHERE collection_id=3002))::text,'Public collection 3002 is visible to Cy'
UNION ALL SELECT 'duplicate_item_prevented','item:5003',(NOT EXISTS(SELECT 1 FROM visible_items WHERE item_id=5003))::text,'Duplicate attempt item 5003 is not active collection content'
UNION ALL SELECT 'collection_item_order','collection:3001',COALESCE((SELECT string_agg(item_id::text,'>' ORDER BY item_position,item_id) FROM visible_items WHERE collection_id=3001),'none'),'Collection item order uses item_position and suppresses hidden items'
UNION ALL SELECT 'deleted_item_hidden','item:5005',(NOT EXISTS(SELECT 1 FROM visible_items WHERE item_id=5005))::text,'Item 5005 points at deleted post 1002'
UNION ALL SELECT 'blocked_author_item_hidden','item:5004',(NOT EXISTS(SELECT 1 FROM visible_items WHERE item_id=5004))::text,'Item 5004 points at blocked seller Ben and hide treatment 8001'
UNION ALL SELECT 'collaborative_member_add_allowed','member:4001',(EXISTS(SELECT 1 FROM collection_members WHERE member_id=4001 AND member_state='active' AND can_add))::text,'Diya member row 4001 can add to collection 3001')
SELECT contract_name,subject_id,observed_value,expected_reason FROM checks ORDER BY contract_name;
