SET search_path TO bip_pim_040;
CREATE TABLE users(user_id int PRIMARY KEY, display_name text NOT NULL);
CREATE TABLE topics(topic_id int PRIMARY KEY, topic_name text NOT NULL, topic_type text NOT NULL CHECK(topic_type IN ('system','user_created','hashtag')));
CREATE TABLE hashtags(hashtag_id int PRIMARY KEY, raw_text text NOT NULL, normalized_text text NOT NULL, topic_id int NOT NULL REFERENCES topics(topic_id));
CREATE TABLE creators(creator_id int PRIMARY KEY, user_id int NOT NULL REFERENCES users(user_id), creator_name text NOT NULL);
CREATE TABLE posts(post_id int PRIMARY KEY, creator_id int NOT NULL REFERENCES creators(creator_id), title text NOT NULL, topic_id int NOT NULL REFERENCES topics(topic_id), content_state text NOT NULL CHECK(content_state IN ('active','deleted','hidden','downranked')));
CREATE TABLE listings(listing_id int PRIMARY KEY, creator_id int NOT NULL REFERENCES creators(creator_id), title text NOT NULL, topic_id int NOT NULL REFERENCES topics(topic_id), listing_state text NOT NULL CHECK(listing_state IN ('active','deleted','hidden','downranked')));
CREATE TABLE content_topic_links(link_id int PRIMARY KEY, topic_id int NOT NULL REFERENCES topics(topic_id), post_id int NOT NULL REFERENCES posts(post_id));
CREATE TABLE creator_topic_links(link_id int PRIMARY KEY, topic_id int NOT NULL REFERENCES topics(topic_id), creator_id int NOT NULL REFERENCES creators(creator_id));
CREATE TABLE user_topic_follows(follow_id int PRIMARY KEY, user_id int NOT NULL REFERENCES users(user_id), topic_id int NOT NULL REFERENCES topics(topic_id), follow_state text NOT NULL CHECK(follow_state IN ('active','paused')));
CREATE TABLE search_sessions(session_id int PRIMARY KEY, user_id int NOT NULL REFERENCES users(user_id));
CREATE TABLE search_queries(query_id int PRIMARY KEY, session_id int NOT NULL REFERENCES search_sessions(session_id), user_id int NOT NULL REFERENCES users(user_id), query_text text NOT NULL);
CREATE TABLE search_filters(filter_id int PRIMARY KEY, query_id int NOT NULL REFERENCES search_queries(query_id), filter_name text NOT NULL, filter_value text NOT NULL);
CREATE TABLE search_facets(facet_id int PRIMARY KEY, query_id int NOT NULL REFERENCES search_queries(query_id), facet_name text NOT NULL, facet_value text NOT NULL);
CREATE TABLE saved_searches(saved_search_id int PRIMARY KEY, user_id int NOT NULL REFERENCES users(user_id), query_text text NOT NULL, saved_state text NOT NULL CHECK(saved_state IN ('active','paused')));
CREATE TABLE interaction_events(event_id int PRIMARY KEY, topic_id int NOT NULL REFERENCES topics(topic_id), actor_user_id int NOT NULL, event_type text NOT NULL);
CREATE TABLE trend_windows(window_id int PRIMARY KEY, window_label text NOT NULL);
CREATE TABLE trend_signal_components(component_id int PRIMARY KEY, window_id int NOT NULL REFERENCES trend_windows(window_id), topic_id int NOT NULL REFERENCES topics(topic_id), component_name text NOT NULL, component_value int NOT NULL);
CREATE TABLE trend_snapshots(snapshot_id int PRIMARY KEY, window_id int NOT NULL REFERENCES trend_windows(window_id), topic_id int NOT NULL REFERENCES topics(topic_id), component_total int NOT NULL);
CREATE TABLE collections(collection_id int PRIMARY KEY, owner_user_id int NOT NULL REFERENCES users(user_id), collection_name text NOT NULL, collection_type text NOT NULL CHECK(collection_type IN ('playlist','bookmark_folder','collection')), visibility text NOT NULL CHECK(visibility IN ('public','private','followers_only')));
CREATE TABLE collection_members(member_id int PRIMARY KEY, collection_id int NOT NULL REFERENCES collections(collection_id), user_id int NOT NULL REFERENCES users(user_id), member_state text NOT NULL CHECK(member_state IN ('active','removed')));
CREATE TABLE collection_items(item_id int PRIMARY KEY, collection_id int NOT NULL REFERENCES collections(collection_id), entity_type text NOT NULL, entity_id int NOT NULL, item_position int NOT NULL, item_state text NOT NULL CHECK(item_state IN ('active','removed','duplicate_attempt')));
CREATE TABLE saved_items(saved_item_id int PRIMARY KEY, user_id int NOT NULL REFERENCES users(user_id), entity_type text NOT NULL, entity_id int NOT NULL, saved_state text NOT NULL CHECK(saved_state IN ('active','removed')));
CREATE TABLE block_edges(block_id int PRIMARY KEY, blocker_user_id int NOT NULL REFERENCES users(user_id), blocked_user_id int NOT NULL REFERENCES users(user_id));
CREATE TABLE policy_treatments(treatment_id int PRIMARY KEY, entity_type text NOT NULL, entity_id int NOT NULL, treatment text NOT NULL CHECK(treatment IN ('allow','downrank','hide','review')), reason text NOT NULL);
CREATE TABLE abuse_signal_events(signal_id int PRIMARY KEY, topic_id int NOT NULL REFERENCES topics(topic_id), signal_type text NOT NULL, signal_count int NOT NULL);
