SET search_path TO bip_pim_040;
WITH followed_topics AS (SELECT * FROM user_topic_follows WHERE user_id=1 AND follow_state='active'), blocked AS (SELECT blocked_user_id FROM block_edges WHERE blocker_user_id=1), topic_surface AS (SELECT p.post_id FROM followed_topics ft JOIN content_topic_links ctl ON ctl.topic_id=ft.topic_id JOIN posts p ON p.post_id=ctl.post_id JOIN creators c ON c.creator_id=p.creator_id WHERE p.content_state='active' AND NOT EXISTS(SELECT 1 FROM blocked b WHERE b.blocked_user_id=c.user_id)), q AS (SELECT * FROM search_queries WHERE query_id=9001), filters AS (SELECT * FROM search_filters WHERE query_id=9001), raw_results AS (SELECT 'post' entity_type,post_id entity_id,creator_id,title,topic_id,content_state state FROM posts WHERE title ILIKE '%'||(SELECT query_text FROM q)||'%' UNION ALL SELECT 'listing',listing_id,creator_id,title,topic_id,listing_state FROM listings WHERE title ILIKE '%'||(SELECT query_text FROM q)||'%'), search_results AS (SELECT r.* FROM raw_results r JOIN creators c ON c.creator_id=r.creator_id LEFT JOIN policy_treatments pt ON pt.entity_type=r.entity_type AND pt.entity_id=r.entity_id WHERE r.state='active' AND COALESCE(pt.treatment,'allow') <> 'hide' AND NOT EXISTS(SELECT 1 FROM blocked b WHERE b.blocked_user_id=c.user_id) AND NOT EXISTS(SELECT 1 FROM filters f WHERE (f.filter_name='result_type' AND r.entity_type<>f.filter_value) OR (f.filter_name='topic_id' AND r.topic_id::text<>f.filter_value))), facet_counts AS (SELECT topic_id,count(*) ct FROM search_results GROUP BY topic_id), trend_totals AS (SELECT topic_id,sum(component_value) total FROM trend_signal_components WHERE window_id=11001 GROUP BY topic_id), suppressed_topics AS (SELECT entity_id topic_id FROM policy_treatments WHERE entity_type='topic' AND treatment='hide'), allowed_trends AS (SELECT * FROM trend_totals t WHERE NOT EXISTS(SELECT 1 FROM suppressed_topics s WHERE s.topic_id=t.topic_id)), visible_collections AS (SELECT * FROM collections c WHERE c.visibility='public' OR c.owner_user_id=1 OR EXISTS(SELECT 1 FROM collection_members cm WHERE cm.collection_id=c.collection_id AND cm.user_id=1 AND cm.member_state='active')), visible_collection_items AS (SELECT ci.* FROM collection_items ci JOIN visible_collections vc USING(collection_id) WHERE ci.item_state='active'), checks AS (
SELECT 'topic_discovery_contract' contract_name,'topic:101' subject_id,COALESCE((SELECT string_agg(post_id::text,'|' ORDER BY post_id) FROM topic_surface),'none') observed_value,'Ada follow 5001 and content_topic_links produce visible topic posts' expected_reason
UNION ALL SELECT 'search_result_contract','query:9001',COALESCE((SELECT string_agg(entity_type||':'||entity_id,'|' ORDER BY entity_type,entity_id) FROM search_results),'none'),'Search query 9001 applies filters and visibility before results'
UNION ALL SELECT 'filter_facet_contract','facet:9151','filters='||(SELECT string_agg(filter_name||'='||filter_value,'|' ORDER BY filter_id) FROM filters)||'|facet='||COALESCE((SELECT string_agg(topic_id||':'||ct,'|' ORDER BY topic_id) FROM facet_counts),'none'),'Facet counts derive from filtered visible results'
UNION ALL SELECT 'saved_search_contract','saved:9202',(NOT EXISTS(SELECT 1 FROM saved_searches WHERE saved_search_id=9202 AND saved_state='active'))::text,'Paused saved search 9202 does not alert in base data'
UNION ALL SELECT 'trending_component_contract','window:11001',string_agg(topic_id||':'||total,'|' ORDER BY topic_id),'Trend totals derive from signal component rows' FROM trend_totals
UNION ALL SELECT 'safety_suppression_contract','topic:102',(NOT EXISTS(SELECT 1 FROM allowed_trends WHERE topic_id=102))::text,'Topic 102 is suppressed by abuse signal 15001 and treatment 16001'
UNION ALL SELECT 'collection_visibility_contract','collection:12001',(EXISTS(SELECT 1 FROM visible_collections WHERE collection_id=12001))::text,'Ada can see owner-private collection 12001'
UNION ALL SELECT 'collection_item_lifecycle_contract','collection:12001',COALESCE((SELECT string_agg(item_id::text,'>' ORDER BY item_position,item_id) FROM visible_collection_items WHERE collection_id=12001),'none'),'Collection items include active ordered rows and exclude duplicate item 13003'
UNION ALL SELECT 'discovery_debug_trace_contract','user:1','topic='||COALESCE((SELECT string_agg(post_id::text,'|' ORDER BY post_id) FROM topic_surface),'none')||'|search='||COALESCE((SELECT string_agg(entity_type||':'||entity_id,'|' ORDER BY entity_type,entity_id) FROM search_results),'none')||'|trends='||COALESCE((SELECT string_agg(topic_id||':'||total,'|' ORDER BY topic_id) FROM allowed_trends),'none')||'|collection='||COALESCE((SELECT string_agg(item_id::text,'>' ORDER BY item_position,item_id) FROM visible_collection_items WHERE collection_id=12001),'none'),'Trace combines topics, search, filters, facets, saved searches, trend components, safety, and collections')
SELECT contract_name,subject_id,observed_value,expected_reason FROM checks ORDER BY contract_name;
