-- Wrong pattern 1: relying on SELECT * instead of returning a shaped backend result.
-- Wrong pattern 2: forgetting the visibility or exclusion predicate that protects the viewer.
-- Wrong pattern 3: joining tables in a way that duplicates rows and inflates counts.
-- Wrong pattern 4: leaving correctness to application code when a database rule is available.
