SET search_path TO bip_pim_030;
WITH current_body AS (SELECT m.message_id,COALESCE((SELECT edited_body FROM message_edits e WHERE e.message_id=m.message_id ORDER BY edit_seq DESC LIMIT 1),m.body) body FROM messages m), visible AS (SELECT m.* FROM messages m JOIN conversation_participants p ON p.conversation_id=m.conversation_id AND p.user_id=1 WHERE NOT EXISTS(SELECT 1 FROM message_deletions d WHERE d.message_id=m.message_id AND (d.delete_scope='for_everyone' OR (d.delete_scope='for_me' AND d.viewer_user_id=1))) AND NOT EXISTS(SELECT 1 FROM block_edges b WHERE b.blocker_user_id=1 AND b.blocked_user_id=m.sender_user_id)), unread AS (SELECT count(*) unread_count FROM visible v LEFT JOIN message_read_receipts r ON r.conversation_id=v.conversation_id AND r.user_id=1 WHERE v.conversation_id=101 AND v.sender_user_id<>1 AND v.message_seq>COALESCE(r.latest_read_seq,0)), inbox AS (SELECT conversation_id,max(sent_rank) latest_rank FROM visible GROUP BY conversation_id), checks AS (
SELECT 'participant_contract' contract_name,'conversation:101' subject_id,count(*)::text observed_value,'Conversation 101 has Ada and Ben participant source rows' expected_reason FROM conversation_participants WHERE conversation_id=101 AND participant_state='active'
UNION ALL SELECT 'message_visibility_contract','message:1003',(NOT EXISTS(SELECT 1 FROM visible WHERE message_id=1003))::text,'Ada delete-for-me row hides message 1003 only for Ada'
UNION ALL SELECT 'delivery_read_contract','message:1001',(SELECT delivery_state FROM message_delivery_states WHERE delivery_id=2001),'Delivery/read state is stored per recipient'
UNION ALL SELECT 'unread_count_contract','conversation:101',(SELECT unread_count::text FROM unread),'Unread count derives from Ada read receipt and visible non-sender messages'
UNION ALL SELECT 'edit_delete_contract','message:1002',(SELECT body FROM current_body WHERE message_id=1002),'Current body comes from latest edit while delete rows stay separate'
UNION ALL SELECT 'attachment_contract','attachment:3001',(EXISTS(SELECT 1 FROM message_attachments a JOIN visible v ON v.message_id=a.message_id WHERE a.attachment_id=3001))::text,'Attachment visibility follows visible message 1002'
UNION ALL SELECT 'inbox_order_contract','user:Ada',string_agg(conversation_id::text,'>' ORDER BY latest_rank DESC, conversation_id DESC),'Inbox order is per-user and deterministic' FROM inbox
UNION ALL SELECT 'mute_block_contract','conversation:102',(SELECT CASE WHEN muted THEN 'muted' ELSE 'unmuted' END FROM conversation_user_settings WHERE conversation_id=102 AND user_id=1)||':blocked_cy='||(EXISTS(SELECT 1 FROM block_edges WHERE blocker_user_id=1 AND blocked_user_id=3))::text,'Mute and block rows alter communication read behavior'
UNION ALL SELECT 'report_review_contract','message:1004',(EXISTS(SELECT 1 FROM message_reports r JOIN review_queue_items q USING(message_id) WHERE r.message_id=1004))::text,'Report row links to review queue item 8001'
UNION ALL SELECT 'communication_debug_trace_contract','user:Ada','visible='||(SELECT string_agg(message_id::text,'|' ORDER BY message_id) FROM visible)||'|unread='||(SELECT unread_count FROM unread)||'|inbox='||(SELECT string_agg(conversation_id::text,'>' ORDER BY latest_rank DESC, conversation_id DESC) FROM inbox),'Trace combines participants, visibility, read state, inbox, block, mute, and report state')
SELECT contract_name,subject_id,observed_value,expected_reason FROM checks ORDER BY contract_name;
