SET search_path TO bip_pim_031;
WITH active_members AS (SELECT * FROM community_memberships WHERE member_state='active'), banned AS (SELECT * FROM community_bans), role_permissions AS (SELECT ra.community_id,ra.user_id,r.role_name,p.permission_name,p.is_allowed,ra.assignment_id,p.permission_id FROM community_role_assignments ra JOIN community_roles r USING(role_id) JOIN community_permissions p ON p.role_id=r.role_id AND p.community_id=ra.community_id), checks AS (
SELECT 'active_member_visible' contract_name,'user:'||user_id subject_id,(EXISTS(SELECT 1 FROM active_members am WHERE am.community_id=101 AND am.user_id=1 AND NOT EXISTS(SELECT 1 FROM banned b WHERE b.community_id=am.community_id AND b.user_id=am.user_id)))::text observed_value,'Ada membership 1001 is active and not banned' expected_reason FROM users WHERE user_id=1
UNION ALL SELECT 'left_member_hidden','user:'||user_id,(NOT EXISTS(SELECT 1 FROM active_members WHERE community_id=101 AND user_id=3))::text,'Cy membership 1003 is left, so member-only content is hidden' FROM users WHERE user_id=3
UNION ALL SELECT 'banned_member_blocked','user:'||user_id,(EXISTS(SELECT 1 FROM banned WHERE community_id=101 AND user_id=4))::text,'Diya ban 7001 blocks private content and rejoin' FROM users WHERE user_id=4
UNION ALL SELECT 'owner_role_contract','user:'||user_id,(SELECT role_name FROM role_permissions rp WHERE rp.user_id=1 AND rp.permission_name='transfer_ownership' AND rp.is_allowed),'Owner role 201 can transfer ownership' FROM users WHERE user_id=1
UNION ALL SELECT 'moderator_permission_contract','user:'||user_id,(SELECT is_allowed::text FROM role_permissions rp WHERE rp.user_id=2 AND rp.permission_name='remove_post'),'Moderator permission row 9002 controls remove_post' FROM users WHERE user_id=2
UNION ALL SELECT 'member_permission_denied','user:'||user_id,(SELECT is_allowed::text FROM role_permissions rp WHERE rp.user_id=5 AND rp.permission_name='remove_post'),'Member role 204 has permission 9004 denied' FROM users WHERE user_id=5
UNION ALL SELECT 'role_permission_trace','community:101',string_agg(role_name||':'||permission_name||'='||is_allowed::text,'|' ORDER BY role_name,permission_name),'Trace comes from role assignments and permission rows' FROM role_permissions WHERE community_id=101
UNION ALL SELECT 'membership_lifecycle_trace','community:101',string_agg(user_id||':'||member_state,'|' ORDER BY membership_id),'Membership rows distinguish active, left, and banned states' FROM community_memberships WHERE community_id=101)
SELECT contract_name,subject_id,observed_value,expected_reason FROM checks ORDER BY contract_name;
