SET search_path TO bip_pim_037;
WITH q AS (SELECT * FROM search_queries WHERE query_id=1001), filters AS (SELECT * FROM search_filters WHERE query_id=1001), blocked AS (SELECT blocked_user_id FROM block_edges WHERE blocker_user_id=1), raw_results AS (SELECT 'post' entity_type,post_id entity_id,creator_id,title,topic_id,content_state state FROM posts WHERE title ILIKE '%'||(SELECT query_text FROM q)||'%' UNION ALL SELECT 'listing',listing_id,creator_id,title,topic_id,listing_state FROM listings WHERE title ILIKE '%'||(SELECT query_text FROM q)||'%'), visible_results AS (SELECT r.* FROM raw_results r JOIN creators c ON c.creator_id=r.creator_id LEFT JOIN content_treatments t ON t.entity_type=r.entity_type AND t.entity_id=r.entity_id WHERE r.state='active' AND COALESCE(t.treatment,'allow') <> 'hide' AND NOT EXISTS(SELECT 1 FROM blocked b WHERE b.blocked_user_id=c.user_id)), filtered_results AS (SELECT * FROM visible_results r WHERE NOT EXISTS(SELECT 1 FROM filters f WHERE (f.filter_name='result_type' AND r.entity_type<>f.filter_value) OR (f.filter_name='topic_id' AND r.topic_id::text<>f.filter_value))), facet_counts AS (SELECT topic_id,count(*) ct FROM filtered_results GROUP BY topic_id), checks AS (
SELECT 'query_recorded' contract_name,'query:1001' subject_id,query_text observed_value,'Search query 1001 records Ada text workshop' expected_reason FROM q
UNION ALL SELECT 'filter_applied','query:1001',string_agg(filter_name||'='||filter_value,'|' ORDER BY filter_id),'Filters 2001 and 2002 constrain result type and topic' FROM filters
UNION ALL SELECT 'facet_count','facet:3001',COALESCE((SELECT ct::text FROM facet_counts WHERE topic_id=501),'0'),'Facet count derives from visible filtered results for topic 501'
UNION ALL SELECT 'saved_search_contract','saved:4001',(SELECT saved_state||':'||query_text||':'||filter_name||'='||filter_value FROM saved_searches WHERE saved_search_id=4001),'Saved search 4001 stores query and filter state'
UNION ALL SELECT 'paused_saved_search_no_alert','saved:4002',(NOT EXISTS(SELECT 1 FROM saved_searches WHERE saved_search_id=4002 AND saved_state='active'))::text,'Paused saved search 4002 does not alert'
UNION ALL SELECT 'unsafe_result_suppressed','listing:6001',(NOT EXISTS(SELECT 1 FROM filtered_results WHERE entity_type='listing' AND entity_id=6001))::text,'Listing 6001 is hidden by treatment 8001 and blocked creator 701'
UNION ALL SELECT 'search_debug_trace','query:1001','results='||COALESCE((SELECT string_agg(entity_type||':'||entity_id,'|' ORDER BY entity_type,entity_id) FROM filtered_results),'none')||'|facets='||COALESCE((SELECT string_agg(topic_id||':'||ct,'|' ORDER BY topic_id) FROM facet_counts),'none')||'|alertable='||(EXISTS(SELECT 1 FROM saved_searches WHERE saved_search_id=4001 AND saved_state='active'))::text,'Trace combines query, filters, visible results, facets, saved search, blocks, and treatments')
SELECT contract_name,subject_id,observed_value,expected_reason FROM checks ORDER BY contract_name;
