SET search_path TO bip_pim_035;
WITH active_members AS (SELECT * FROM community_memberships m WHERE member_state='active' AND NOT EXISTS(SELECT 1 FROM community_bans b WHERE b.community_id=m.community_id AND b.user_id=m.user_id)), role_permissions AS (SELECT ra.user_id,r.role_name,p.permission_name,p.is_allowed FROM community_role_assignments ra JOIN community_roles r USING(role_id) JOIN community_permissions p ON p.role_id=r.role_id AND p.community_id=ra.community_id), visible_posts AS (SELECT viewer.user_id viewer_user_id,p.* FROM active_members viewer JOIN community_posts p ON p.community_id=viewer.community_id JOIN community_channels ch ON ch.channel_id=p.channel_id WHERE p.post_state='active' AND NOT EXISTS(SELECT 1 FROM community_post_moderation_actions ma WHERE ma.post_id=p.post_id AND ma.action_type IN ('hide','remove')) AND (ch.channel_visibility='public' OR EXISTS(SELECT 1 FROM channel_memberships cm WHERE cm.channel_id=ch.channel_id AND cm.user_id=viewer.user_id AND cm.channel_member_state='active'))), eligible_rsvps AS (SELECT r.* FROM event_rsvps r JOIN community_events e USING(event_id) WHERE e.event_state='scheduled' AND (NOT e.member_only OR EXISTS(SELECT 1 FROM active_members m WHERE m.community_id=e.community_id AND m.user_id=r.user_id))), going_counts AS (SELECT event_id,count(*) going_count FROM eligible_rsvps WHERE rsvp_state='going' GROUP BY event_id), valid_attendance AS (SELECT a.* FROM event_attendance a JOIN event_rsvps r ON r.rsvp_id=a.rsvp_id AND r.user_id=a.user_id AND r.event_id=a.event_id AND r.rsvp_state='going'), checks AS (
SELECT 'membership_contract' contract_name,'community:101' subject_id,string_agg(user_id||':'||member_state,'|' ORDER BY membership_id) observed_value,'Active membership rows 2001, 2002, and 2005 gate community access' expected_reason FROM community_memberships WHERE community_id=101
UNION ALL SELECT 'role_permission_contract','user:2',string_agg(permission_name||'='||is_allowed::text,'|' ORDER BY permission_name),'Ben moderator permissions come from role 6002 rows 6202 and 6203' FROM role_permissions WHERE user_id=2
UNION ALL SELECT 'private_access_contract','community:101',string_agg(user_id::text,'|' ORDER BY user_id),'Private access includes active non-banned members and excludes Cy request 3003 and Diya ban 5004' FROM active_members WHERE community_id=101
UNION ALL SELECT 'channel_visibility_contract','user:2',string_agg(post_id::text,'|' ORDER BY post_id),'Ben sees public post 8001, private mod post 8002, and reply 8004 but not removed post 8003' FROM visible_posts WHERE viewer_user_id=2
UNION ALL SELECT 'post_thread_contract','thread:8501',(SELECT parent_post_id||'->'||reply_post_id FROM community_threads WHERE thread_id=8501),'Thread 8501 keeps reply 8004 attached to post 8001'
UNION ALL SELECT 'moderation_audit_contract','post:8003',(EXISTS(SELECT 1 FROM community_post_moderation_actions ma JOIN community_audit_log al ON al.entity_type='post' AND al.entity_id=ma.post_id AND al.action_type=ma.action_type WHERE ma.post_id=8003 AND ma.action_type='remove'))::text,'Moderation action 10003 has audit row 11003'
UNION ALL SELECT 'event_rsvp_contract','event:9001',string_agg(user_id||':'||rsvp_state,'|' ORDER BY rsvp_id),'RSVP rows separate going and waitlisted states' FROM eligible_rsvps WHERE event_id=9001
UNION ALL SELECT 'waitlist_capacity_contract','event:9001','going='||COALESCE((SELECT going_count::text FROM going_counts WHERE event_id=9001),'0')||'|capacity='||(SELECT capacity FROM community_events WHERE event_id=9001)||'|waitlist='||(SELECT string_agg(user_id||':'||waitlist_state,'|' ORDER BY waitlist_rank) FROM event_waitlist WHERE event_id=9001),'Capacity counts going only and keeps waitlist lifecycle separate'
UNION ALL SELECT 'attendance_contract','attendance:9401',(EXISTS(SELECT 1 FROM valid_attendance WHERE attendance_id=9401))::text,'Attendance 9401 links to Ada going RSVP 9201'
UNION ALL SELECT 'community_debug_trace_contract','community:101','members='||(SELECT string_agg(user_id::text,'|' ORDER BY user_id) FROM active_members WHERE community_id=101)||'|visible_ben='||(SELECT string_agg(post_id::text,'|' ORDER BY post_id) FROM visible_posts WHERE viewer_user_id=2)||'|going='||COALESCE((SELECT going_count::text FROM going_counts WHERE event_id=9001),'0')||'|audit='||(SELECT string_agg(action_type,'|' ORDER BY audit_id) FROM community_audit_log WHERE community_id=101),'Debug trace combines membership, roles, access, channel posts, moderation, RSVP, waitlist, attendance, and audit')
SELECT contract_name,subject_id,observed_value,expected_reason FROM checks ORDER BY contract_name;
