SET search_path TO bip_pim_025;
CREATE TABLE buyers (buyer_id int PRIMARY KEY, display_name text NOT NULL);
CREATE TABLE sellers (seller_id int PRIMARY KEY, display_name text NOT NULL);
CREATE TABLE creators (creator_id int PRIMARY KEY, display_name text NOT NULL, popularity int NOT NULL);
CREATE TABLE creator_profiles (creator_id int PRIMARY KEY REFERENCES creators, status text NOT NULL);
CREATE TABLE creator_content (content_id int PRIMARY KEY, creator_id int REFERENCES creators, status text NOT NULL);
CREATE TABLE exposure_budget_windows (window_id int PRIMARY KEY, creator_id int REFERENCES creators, budget_limit int NOT NULL);
CREATE TABLE exposure_events (event_id int PRIMARY KEY, creator_id int REFERENCES creators);
CREATE TABLE buyer_intents (intent_id int PRIMARY KEY, buyer_id int REFERENCES buyers, category text NOT NULL, max_price int NOT NULL, location text NOT NULL);
CREATE TABLE listings (listing_id int PRIMARY KEY, seller_id int REFERENCES sellers, category text NOT NULL, price int NOT NULL, location text NOT NULL, status text NOT NULL, popularity int NOT NULL);
CREATE TABLE listing_tags (listing_id int REFERENCES listings, tag text NOT NULL);
CREATE TABLE listing_availability (availability_id int PRIMARY KEY, listing_id int REFERENCES listings, available_state text NOT NULL);
CREATE TABLE offers (offer_id int PRIMARY KEY, buyer_id int REFERENCES buyers, listing_id int REFERENCES listings, offer_state text NOT NULL);
CREATE TABLE bookings (booking_id int PRIMARY KEY, offer_id int REFERENCES offers, booking_state text NOT NULL);
CREATE TABLE orders (order_id int PRIMARY KEY, seller_id int REFERENCES sellers, order_state text NOT NULL);
CREATE TABLE seller_response_events (response_id int PRIMARY KEY, seller_id int REFERENCES sellers, response_minutes int NOT NULL);
CREATE TABLE seller_reviews (review_id int PRIMARY KEY, seller_id int REFERENCES sellers, rating int NOT NULL);
CREATE TABLE disputes (dispute_id int PRIMARY KEY, seller_id int REFERENCES sellers, state text NOT NULL);
CREATE TABLE seller_quality_components (component_id int PRIMARY KEY, seller_id int REFERENCES sellers, component_type text NOT NULL, component_value int NOT NULL);
CREATE TABLE seller_trust_components (component_id int PRIMARY KEY, seller_id int REFERENCES sellers, component_type text NOT NULL, component_value int NOT NULL);
CREATE TABLE local_supply_snapshots (snapshot_id int PRIMARY KEY, category text NOT NULL, location text NOT NULL, supply_count int NOT NULL);
CREATE TABLE local_demand_snapshots (snapshot_id int PRIMARY KEY, category text NOT NULL, location text NOT NULL, demand_count int NOT NULL);
CREATE TABLE marketplace_risk_events (risk_id int PRIMARY KEY, listing_id int REFERENCES listings, risk_type text NOT NULL, evidence_count int NOT NULL);
CREATE TABLE marketplace_treatments (treatment_id int PRIMARY KEY, listing_id int REFERENCES listings, treatment text NOT NULL, reason text NOT NULL);
