SET search_path TO bip_pim_025;
WITH exposure AS (SELECT c.creator_id,c.display_name,b.budget_limit-count(e.event_id) remaining FROM creators c JOIN exposure_budget_windows b ON b.creator_id=c.creator_id LEFT JOIN exposure_events e ON e.creator_id=c.creator_id GROUP BY c.creator_id,c.display_name,b.budget_limit), quality AS (SELECT seller_id,sum(component_value) total,string_agg(component_type||':'||component_value,'|' ORDER BY component_type) trace FROM seller_quality_components GROUP BY seller_id), trust AS (SELECT seller_id,sum(component_value) total FROM seller_trust_components GROUP BY seller_id), pressure AS (SELECT d.demand_count-s.supply_count pressure FROM local_supply_snapshots s JOIN local_demand_snapshots d USING(category,location) WHERE s.category='cleaning' AND s.location='North'), listing_fit AS (SELECT l.listing_id,l.seller_id,CASE WHEN l.category=i.category AND l.price<=i.max_price AND l.location=i.location THEN 'match' ELSE 'miss' END fit FROM listings l JOIN buyer_intents i ON i.buyer_id=10), checks AS (
SELECT 'creator_exposure_contract' contract_name,'creator:'||display_name subject_id,remaining::text observed_value,'Creator exposure contract derives remaining budget from exposure events' expected_reason FROM exposure WHERE display_name='MegaMaker'
UNION ALL SELECT 'buyer_intent_contract','buyer:Ada',category||':'||max_price||':'||location,'Buyer intent row drives listing relevance' FROM buyer_intents WHERE buyer_id=10
UNION ALL SELECT 'listing_relevance_contract','listing:'||listing_id,fit,'Listing 1001 matches Ada category, price, and location intent' FROM listing_fit WHERE listing_id=1001
UNION ALL SELECT 'seller_quality_contract','seller:RiskSeller',trace,'Seller quality contract exposes component rows' FROM quality q JOIN sellers s ON s.seller_id=q.seller_id WHERE s.display_name='RiskSeller'
UNION ALL SELECT 'offer_booking_contract','offer:1201',CASE WHEN NOT EXISTS (SELECT 1 FROM bookings WHERE offer_id=1201) THEN 'pending_not_booking' ELSE 'booking' END,'Pending offer is distinct from accepted booking lifecycle' FROM buyers WHERE buyer_id=10
UNION ALL SELECT 'supply_demand_contract','cleaning:North',pressure::text,'Supply demand contract derives demand pressure' FROM pressure
UNION ALL SELECT 'marketplace_risk_contract','listing:1002',risk_type||':'||evidence_count,'Marketplace risk keeps evidence count visible' FROM marketplace_risk_events WHERE listing_id=1002
UNION ALL SELECT 'treatment_contract','listing:'||listing_id,treatment||':'||reason,'Treatment row records boost/downrank/allow reason' FROM marketplace_treatments WHERE listing_id=1002
UNION ALL SELECT 'marketplace_debug_trace_contract','buyer:Ada','exposure='||(SELECT remaining FROM exposure WHERE display_name='MegaMaker')||'|fit='||(SELECT fit FROM listing_fit WHERE listing_id=1001)||'|risk='||(SELECT evidence_count FROM marketplace_risk_events WHERE listing_id=1002)||'|treatment='||(SELECT treatment FROM marketplace_treatments WHERE listing_id=1002),'Trace combines exposure, intent, quality, supply demand, risk, and treatment components') SELECT contract_name,subject_id,observed_value,expected_reason FROM checks ORDER BY contract_name;
