SET search_path TO bip_pim_028;
WITH current_body AS (SELECT m.message_id,COALESCE((SELECT edited_body FROM message_edits e WHERE e.message_id=m.message_id ORDER BY edit_seq DESC LIMIT 1),m.original_body) body FROM messages m), visible AS (SELECT m.message_id, NOT EXISTS(SELECT 1 FROM message_deletions d WHERE d.message_id=m.message_id AND (d.delete_scope='for_everyone' OR (d.delete_scope='for_me' AND d.viewer_user_id=1))) ada_visible, NOT EXISTS(SELECT 1 FROM message_deletions d WHERE d.message_id=m.message_id AND (d.delete_scope='for_everyone' OR (d.delete_scope='for_me' AND d.viewer_user_id=2))) ben_visible FROM messages m), checks AS (
SELECT 'latest_edit_current_body' contract_name,'message:1001' subject_id,body observed_value,'Latest edit row determines current body' expected_reason FROM current_body WHERE message_id=1001
UNION ALL SELECT 'edit_history_preserved','message:1001',count(*)::text,'Edit history rows remain queryable' FROM message_edits WHERE message_id=1001
UNION ALL SELECT 'delete_for_me_viewer_hidden','message:1002',(SELECT ada_visible::text FROM visible WHERE message_id=1002),'Delete-for-me hides message 1002 for Ada only'
UNION ALL SELECT 'delete_for_me_other_viewer_visible','message:1002',(SELECT ben_visible::text FROM visible WHERE message_id=1002),'Ben still sees message 1002'
UNION ALL SELECT 'delete_for_everyone_hidden','message:1003',(SELECT ada_visible::text FROM visible WHERE message_id=1003),'Delete-for-everyone hides message 1003 for all viewers'
UNION ALL SELECT 'attachment_visible','attachment:3001',(SELECT ada_visible::text FROM visible v JOIN message_attachments a ON a.message_id=v.message_id WHERE a.attachment_id=3001),'Attachment 3001 is visible because message 1004 is visible'
UNION ALL SELECT 'attachment_hidden_with_message','attachment:3002',(SELECT ada_visible::text FROM visible v JOIN message_attachments a ON a.message_id=v.message_id WHERE a.attachment_id=3002),'Attachment 3002 is hidden with globally deleted message 1003'
UNION ALL SELECT 'message_lifecycle_trace','conversation:101',string_agg(m.message_id||':ada='||v.ada_visible||':ben='||v.ben_visible||':body='||c.body,';' ORDER BY m.message_id),'Trace combines current body, per-user deletion, and global deletion' FROM messages m JOIN visible v USING(message_id) JOIN current_body c USING(message_id))
SELECT contract_name,subject_id,observed_value,expected_reason FROM checks ORDER BY contract_name;
