SET search_path TO bip_pim_026;
WITH active_counts AS (SELECT conversation_id,count(*) FILTER (WHERE participant_state='active') active_count FROM conversation_participants GROUP BY conversation_id), visible_to_ben AS (SELECT m.message_id FROM messages m JOIN conversation_participants p ON p.conversation_id=m.conversation_id AND p.user_id=2 WHERE p.joined_seq<=m.message_seq AND (p.left_seq IS NULL OR m.message_seq<=p.left_seq)), sender_valid AS (SELECT m.message_id, EXISTS (SELECT 1 FROM conversation_participants p WHERE p.conversation_id=m.conversation_id AND p.user_id=m.sender_user_id AND p.joined_seq<=m.message_seq AND (p.left_seq IS NULL OR m.message_seq<=p.left_seq)) valid FROM messages m), checks AS (
SELECT 'direct_conversation_participants' contract_name,'conversation:'||conversation_id subject_id,active_count::text observed_value,'Direct conversation 101 has exactly Ada and Ben active' expected_reason FROM active_counts WHERE conversation_id=101
UNION ALL SELECT 'group_conversation_participants','conversation:'||conversation_id,active_count::text,'Group conversation 102 has multiple active participants' FROM active_counts WHERE conversation_id=102
UNION ALL SELECT 'valid_sender_participant','message:1002',(SELECT valid::text FROM sender_valid WHERE message_id=1002),'Ben can send message 1002 before leaving conversation 102'
UNION ALL SELECT 'non_participant_hidden','user:Diya',(NOT EXISTS (SELECT 1 FROM conversation_participants WHERE conversation_id=102 AND user_id=4))::text,'Diya has no participant row and cannot see conversation 102'
UNION ALL SELECT 'left_participant_future_hidden','message:1003',(NOT EXISTS (SELECT 1 FROM visible_to_ben WHERE message_id=1003))::text,'Ben left before message 1003 in base data'
UNION ALL SELECT 'blocked_direct_conversation_prevented','conversation:103',(EXISTS (SELECT 1 FROM block_edges b JOIN conversation_participants p1 ON p1.user_id=b.blocker_user_id AND p1.conversation_id=103 JOIN conversation_participants p2 ON p2.user_id=b.blocked_user_id AND p2.conversation_id=103))::text,'Ada/Cy block edge prevents a valid direct conversation'
UNION ALL SELECT 'conversation_visibility_trace','conversation:102',string_agg(u.display_name||':'||p.participant_state||':joined='||p.joined_seq||':left='||COALESCE(p.left_seq::text,'none'),';' ORDER BY p.participant_id),'Trace shows participant lifecycle and visibility windows' FROM conversation_participants p JOIN users u ON u.user_id=p.user_id WHERE p.conversation_id=102)
SELECT contract_name,subject_id,observed_value,expected_reason FROM checks ORDER BY contract_name;
