SET search_path TO bip_pim_022;
WITH trust AS (SELECT seller_id,sum(component_value) trust_total FROM seller_trust_components GROUP BY seller_id), scored AS (SELECT l.listing_id,l.title,l.category,l.price,l.location,l.status,l.created_rank,t.trust_total,CASE WHEN l.category=i.category THEN 1 ELSE 0 END cat,CASE WHEN l.price<=i.max_price THEN 1 ELSE 0 END price_ok,CASE WHEN l.location=i.location THEN 1 ELSE 0 END loc,CASE WHEN a.available_state='available' THEN 1 ELSE 0 END avail,CASE WHEN seen.listing_id IS NULL THEN 0 ELSE 1 END seen FROM buyer_intents i JOIN listings l ON l.status='active' JOIN listing_availability a ON a.listing_id=l.listing_id JOIN trust t ON t.seller_id=l.seller_id LEFT JOIN buyer_seen_listings seen ON seen.buyer_id=i.buyer_id AND seen.listing_id=l.listing_id WHERE i.buyer_id=10), selected AS (SELECT * FROM scored WHERE cat=1 AND price_ok=1 AND loc=1 AND avail=1 AND seen=0 AND trust_total>=60 ORDER BY created_rank DESC LIMIT 1), checks AS (
SELECT 'category_match_component' contract_name,'listing:'||listing_id subject_id,cat::text observed_value,'Listing category must match Ada buyer intent' expected_reason FROM scored WHERE listing_id=(SELECT min(listing_id) FROM scored WHERE cat=1)
UNION ALL SELECT 'price_match_component','listing:'||listing_id,price_ok::text,'Price must be at or below buyer intent max_price' FROM scored WHERE listing_id=101
UNION ALL SELECT 'location_match_component','listing:'||listing_id,loc::text,'Location or service area must match buyer intent' FROM scored WHERE listing_id=(SELECT listing_id FROM selected)
UNION ALL SELECT 'availability_match_component','listing:'||listing_id,avail::text,'Listing availability row must be available' FROM scored WHERE listing_id=(SELECT listing_id FROM selected)
UNION ALL SELECT 'already_seen_suppressed','listing:'||listing_id,CASE WHEN seen=1 THEN 'suppressed' ELSE 'visible' END,'Seen listing 102 is suppressed for Ada' FROM scored WHERE listing_id=102
UNION ALL SELECT 'low_trust_seller_suppressed','listing:'||listing_id,CASE WHEN trust_total<60 THEN 'review' ELSE 'allow' END,'RiskSeller listing is reviewed because seller trust components are low' FROM scored WHERE listing_id=103
UNION ALL SELECT 'selected_listing','buyer:Ada','listing:'||listing_id,'Selected listing satisfies intent, availability, seen state, and trust gate' FROM selected
UNION ALL SELECT 'relevance_debug_trace','buyer:Ada',string_agg(listing_id||':cat='||cat||'|price='||price_ok||'|loc='||loc||'|avail='||avail||'|seen='||seen||'|trust='||trust_total,';' ORDER BY listing_id),'Trace lists relevance components and seller trust treatment reason' FROM scored)
SELECT contract_name,subject_id,observed_value,expected_reason FROM checks ORDER BY contract_name;
