SET search_path TO bip_pim_021;
WITH spend AS (SELECT creator_id, count(*) AS spent FROM exposure_events WHERE surface='home' GROUP BY creator_id), quality AS (SELECT creator_id, sum(component_value) AS quality_total FROM creator_quality_components GROUP BY creator_id), enriched AS (SELECT c.creator_id,c.display_name,c.popularity,b.budget_limit,COALESCE(s.spent,0) spent,b.budget_limit-COALESCE(s.spent,0) remaining,q.quality_total,CASE WHEN v.creator_id IS NULL THEN 'no' ELSE 'yes' END AS seen FROM creators c JOIN exposure_budget_windows b ON b.creator_id=c.creator_id LEFT JOIN spend s ON s.creator_id=c.creator_id JOIN quality q ON q.creator_id=c.creator_id LEFT JOIN viewer_seen_events v ON v.creator_id=c.creator_id AND v.viewer_id=10), selected AS (SELECT * FROM enriched WHERE remaining>0 AND quality_total>=50 AND seen='no' ORDER BY CASE WHEN popularity<200 THEN 0 ELSE 1 END, popularity DESC LIMIT 1), checks AS (
SELECT 'popular_creator_capped' contract_name,'creator:'||display_name subject_id,CASE WHEN remaining<=0 THEN 'capped' ELSE 'eligible' END observed_value,'MegaMaker is capped when exposure spend reaches the budget window' expected_reason FROM enriched WHERE display_name='MegaMaker'
UNION ALL SELECT 'long_tail_creator_exposed','creator:'||display_name,CASE WHEN remaining>0 AND quality_total>=50 THEN 'exposed' ELSE 'not_exposed' END,'QuietCraft earns a long-tail slot because budget remains and quality is healthy' FROM enriched WHERE display_name='QuietCraft'
UNION ALL SELECT 'low_quality_creator_not_boosted','creator:'||display_name,CASE WHEN quality_total<50 THEN 'not_boosted' ELSE 'boosted' END,'LowLift is long-tail but blocked by low quality components' FROM enriched WHERE display_name='LowLift'
UNION ALL SELECT 'repeated_creator_suppressed','creator:'||display_name,CASE WHEN seen='yes' THEN 'suppressed' ELSE 'eligible' END,'RepeatRay is suppressed because Ada has already seen the creator' FROM enriched WHERE display_name='RepeatRay'
UNION ALL SELECT 'exposure_budget_remaining','creator:'||display_name,remaining::text,'Budget remaining is budget_limit minus derived exposure spend' FROM enriched WHERE display_name='MegaMaker'
UNION ALL SELECT 'exposure_spend_derived','creator:'||display_name,spent::text,'Exposure spend is counted from exposure_events' FROM enriched WHERE display_name='MegaMaker'
UNION ALL SELECT 'exposure_decision_trace','surface:home',string_agg(display_name||':remaining='||remaining||'|quality='||quality_total||'|seen='||seen,';' ORDER BY creator_id),'Trace shows budget, component quality, and repeated exposure state' FROM enriched
UNION ALL SELECT 'variant_exposure_change','surface:home','creator:'||display_name,'Variant changes the selected creator when MegaMaker has remaining budget' FROM selected)
SELECT contract_name,subject_id,observed_value,expected_reason FROM checks ORDER BY contract_name;
