SET search_path TO bip_pim_036;
WITH followed_topics AS (SELECT * FROM user_topic_follows WHERE user_id=1 AND follow_state='active'), blocked_users AS (SELECT blocked_user_id FROM block_edges WHERE blocker_user_id=1), topic_posts AS (SELECT p.*,ctl.topic_id,COALESCE(ct.treatment,'allow') treatment FROM followed_topics ft JOIN content_topic_links ctl ON ctl.topic_id=ft.topic_id JOIN posts p ON p.post_id=ctl.post_id JOIN creators c ON c.creator_id=p.creator_id LEFT JOIN content_treatments ct ON ct.post_id=p.post_id WHERE p.content_state <> 'deleted' AND NOT EXISTS(SELECT 1 FROM blocked_users b WHERE b.blocked_user_id=c.user_id) AND COALESCE(ct.treatment,'allow') <> 'hide'), topic_creators AS (SELECT c.*,ctl.topic_id FROM followed_topics ft JOIN creator_topic_links ctl ON ctl.topic_id=ft.topic_id JOIN creators c ON c.creator_id=ctl.creator_id WHERE c.creator_state='active' AND NOT EXISTS(SELECT 1 FROM blocked_users b WHERE b.blocked_user_id=c.user_id)), checks AS (
SELECT 'normalized_hashtag_topic' contract_name,'hashtag:'||hashtag_id subject_id,topic_id::text observed_value,'Hashtag 301 normalizes #BuildInPublic to topic 101' expected_reason FROM hashtags WHERE hashtag_id=301
UNION ALL SELECT 'followed_topic_content','user:1',COALESCE(string_agg(post_id::text,'|' ORDER BY post_id),'none'),'Ada sees active followed-topic posts after deletion, block, and treatment rules' FROM topic_posts
UNION ALL SELECT 'followed_topic_creator','user:1',COALESCE(string_agg(creator_id::text,'|' ORDER BY creator_id),'none'),'Ada sees creators linked to active followed topics unless blocked' FROM topic_creators
UNION ALL SELECT 'deleted_content_hidden','post:1002',(NOT EXISTS(SELECT 1 FROM topic_posts WHERE post_id=1002))::text,'Deleted post 1002 is hidden from topic surface'
UNION ALL SELECT 'blocked_creator_hidden','creator:202',(NOT EXISTS(SELECT 1 FROM topic_creators WHERE creator_id=202))::text,'Creator 202 belongs to blocked user Cy via block 6001'
UNION ALL SELECT 'downranked_content_trace','post:1003',(SELECT treatment||':'||reason FROM content_treatments WHERE post_id=1003),'Downranked content remains explainable through treatment 7001'
UNION ALL SELECT 'topic_debug_trace','user:1','topics='||COALESCE((SELECT string_agg(topic_id::text,'|' ORDER BY topic_id) FROM followed_topics),'none')||'|posts='||COALESCE((SELECT string_agg(post_id||':'||treatment,'|' ORDER BY post_id) FROM topic_posts),'none')||'|creators='||COALESCE((SELECT string_agg(creator_id::text,'|' ORDER BY creator_id) FROM topic_creators),'none'),'Trace combines follows, topic links, blocks, deleted state, and treatments')
SELECT contract_name,subject_id,observed_value,expected_reason FROM checks ORDER BY contract_name;
