SET search_path TO bip_pim_023;
WITH comp AS (SELECT s.seller_id,s.display_name,sum(q.component_value) total,string_agg(q.component_type||':'||q.component_value,'|' ORDER BY q.component_type) trace FROM sellers s JOIN seller_quality_components q ON q.seller_id=s.seller_id GROUP BY s.seller_id,s.display_name), checks AS (
SELECT 'fulfilment_component' contract_name,'seller:'||display_name subject_id,(SELECT component_value::text FROM seller_quality_components WHERE seller_id=comp.seller_id AND component_type='fulfilment') observed_value,'Fulfilment component is explicit, not hidden in one seller_quality_score' expected_reason FROM comp WHERE display_name='BrightSeller'
UNION ALL SELECT 'cancellation_component','seller:'||display_name,(SELECT component_value::text FROM seller_quality_components WHERE seller_id=comp.seller_id AND component_type='cancellation'),'Cancellation penalty is a separate component' FROM comp WHERE display_name='RiskSeller'
UNION ALL SELECT 'dispute_component','seller:'||display_name,(SELECT component_value::text FROM seller_quality_components WHERE seller_id=comp.seller_id AND component_type='dispute'),'Dispute penalty is a separate component' FROM comp WHERE display_name='RiskSeller'
UNION ALL SELECT 'response_time_component','seller:'||display_name,(SELECT component_value::text FROM seller_quality_components WHERE seller_id=comp.seller_id AND component_type='response_time'),'Response speed contributes separately' FROM comp WHERE display_name='BrightSeller'
UNION ALL SELECT 'review_component','seller:'||display_name,(SELECT component_value::text FROM seller_quality_components WHERE seller_id=comp.seller_id AND component_type='review'),'Review component contributes separately' FROM comp WHERE display_name='BrightSeller'
UNION ALL SELECT 'seller_quality_total','seller:'||display_name,total::text,'Total derives from seller quality components' FROM comp WHERE display_name='RiskSeller'
UNION ALL SELECT 'seller_treatment','seller:'||s.display_name,qs.treatment,'Treatment derives from the component snapshot' FROM seller_quality_snapshots qs JOIN sellers s ON s.seller_id=qs.seller_id WHERE s.display_name='RiskSeller'
UNION ALL SELECT 'healthy_seller_allowed','seller:'||s.display_name,qs.treatment,'BrightSeller is healthy and boosted/allowed' FROM seller_quality_snapshots qs JOIN sellers s ON s.seller_id=qs.seller_id WHERE s.display_name='BrightSeller'
UNION ALL SELECT 'risky_seller_reviewed','seller:'||s.display_name,qs.treatment,'RiskSeller is reviewed/downranked when component total is poor' FROM seller_quality_snapshots qs JOIN sellers s ON s.seller_id=qs.seller_id WHERE s.display_name='RiskSeller'
UNION ALL SELECT 'quality_debug_trace','seller:'||display_name,trace,'Trace exposes fulfilment, cancellation, dispute, response, and review components' FROM comp WHERE display_name='RiskSeller') SELECT contract_name,subject_id,observed_value,expected_reason FROM checks ORDER BY contract_name;
