SET search_path TO bip_pim_020;
CREATE TABLE users (user_id int PRIMARY KEY, display_name text NOT NULL);
CREATE TABLE profiles (user_id int PRIMARY KEY REFERENCES users, visibility text NOT NULL);
CREATE TABLE posts (post_id int PRIMARY KEY, author_user_id int REFERENCES users, body text NOT NULL);
CREATE TABLE comments (comment_id int PRIMARY KEY, post_id int REFERENCES posts, author_user_id int REFERENCES users, body text NOT NULL);
CREATE TABLE post_reactions (reaction_id int PRIMARY KEY, post_id int REFERENCES posts, actor_user_id int REFERENCES users);
CREATE TABLE follow_edges (follower_user_id int REFERENCES users, followed_user_id int REFERENCES users);
CREATE TABLE block_edges (blocker_user_id int REFERENCES users, blocked_user_id int REFERENCES users);
CREATE TABLE mute_edges (muter_user_id int REFERENCES users, muted_user_id int REFERENCES users);
CREATE TABLE report_events (report_id int PRIMARY KEY, reporter_user_id int REFERENCES users, content_type text NOT NULL, content_id int NOT NULL, reason text NOT NULL);
CREATE TABLE report_evidence (evidence_id int PRIMARY KEY, report_id int REFERENCES report_events, evidence_type text NOT NULL);
CREATE TABLE review_queue_items (queue_item_id int PRIMARY KEY, content_type text NOT NULL, content_id int NOT NULL, state text NOT NULL);
CREATE TABLE policy_decisions (decision_id int PRIMARY KEY, queue_item_id int REFERENCES review_queue_items, policy text NOT NULL, decision text NOT NULL);
CREATE TABLE policy_treatments (treatment_id int PRIMARY KEY, decision_id int REFERENCES policy_decisions, treatment text NOT NULL);
CREATE TABLE moderation_actions (action_id int PRIMARY KEY, post_id int REFERENCES posts, treatment text NOT NULL);
CREATE TABLE appeals (appeal_id int PRIMARY KEY, post_id int REFERENCES posts, state text NOT NULL);
CREATE TABLE appeal_decisions (appeal_decision_id int PRIMARY KEY, appeal_id int REFERENCES appeals, outcome text NOT NULL);
CREATE TABLE audit_log (audit_id int PRIMARY KEY, entity_type text NOT NULL, entity_id int NOT NULL, action text NOT NULL, previous_treatment text, new_treatment text);
CREATE TABLE abuse_signal_events (signal_id int PRIMARY KEY, user_id int REFERENCES users, signal_type text NOT NULL, classification text NOT NULL);
CREATE TABLE abuse_signal_evidence (evidence_id int PRIMARY KEY, signal_id int REFERENCES abuse_signal_events, source_type text NOT NULL, source_id int NOT NULL);
CREATE TABLE trust_score_components (component_id int PRIMARY KEY, user_id int REFERENCES users, component_type text NOT NULL, component_value int NOT NULL);
CREATE TABLE trust_score_snapshots (snapshot_id int PRIMARY KEY, user_id int REFERENCES users, component_total int NOT NULL, treatment text NOT NULL);
