SET search_path TO bip_pim_020;
WITH latest_actions AS (SELECT post_id, string_agg(treatment,'>' ORDER BY action_id) AS action_trace, (array_agg(treatment ORDER BY action_id DESC))[1] AS current_treatment FROM moderation_actions GROUP BY post_id), trust_trace AS (SELECT user_id, sum(component_value) AS total, string_agg(component_type||':'||component_value::text,'|' ORDER BY component_type) AS components FROM trust_score_components GROUP BY user_id), abuse_trace AS (SELECT s.signal_id, s.user_id, string_agg(e.evidence_id::text,'+' ORDER BY e.evidence_id) AS evidence_ids FROM abuse_signal_events s JOIN abuse_signal_evidence e ON e.signal_id=s.signal_id GROUP BY s.signal_id,s.user_id), audit_trace AS (SELECT string_agg(entity_type||':'||entity_id||':'||action,'>' ORDER BY audit_id) AS trace FROM audit_log WHERE audit_id BETWEEN 1301 AND 1304), checks AS (
  SELECT 'visibility_contract' contract_name,'viewer:1' subject_id,COALESCE(string_agg(p.post_id::text,'|' ORDER BY p.post_id),'none') observed_value,'Visible posts exclude current remove actions but keep safe and restored content' expected_reason FROM posts p LEFT JOIN latest_actions la ON la.post_id=p.post_id WHERE COALESCE(la.current_treatment,'allow') <> 'remove'
  UNION ALL SELECT 'review_queue_contract','post:202',count(*)::text,'Reported but unconfirmed post 202 enters review queue item 501' FROM review_queue_items WHERE content_id=202
  UNION ALL SELECT 'policy_decision_contract','post:203',count(*)::text,'Confirmed violation post 203 has fraud decision 602' FROM policy_decisions d JOIN review_queue_items q ON q.queue_item_id=d.queue_item_id WHERE q.content_id=203 AND d.policy='fraud' AND d.decision='violation'
  UNION ALL SELECT 'treatment_contract','post:203',count(*)::text,'Violation decision 602 applies remove treatment 702' FROM policy_treatments WHERE decision_id=602 AND treatment='remove'
  UNION ALL SELECT 'appeal_reversal_contract','post:204',max(action_trace),'Approved appeal restores post 204 after removal' FROM latest_actions WHERE post_id=204
  UNION ALL SELECT 'trust_component_contract','user:3',components,'Cy treatment has report and abuse component breakdown' FROM trust_trace WHERE user_id=3
  UNION ALL SELECT 'abuse_signal_contract','signal:1001',evidence_ids,'Abuse signal 1001 links evidence rows 1201 and 1202' FROM abuse_trace WHERE signal_id=1001
  UNION ALL SELECT 'audit_lineage_contract','trace:1301-1304',trace,'Audit lineage links report to decision to treatment to appeal restore' FROM audit_trace
  UNION ALL SELECT 'safety_debug_trace_contract','user:3',(SELECT treatment FROM trust_score_snapshots WHERE user_id=3)||':'||(SELECT components FROM trust_trace WHERE user_id=3),'Safety debug trace explains final risk treatment from components' FROM users WHERE user_id=3
)
SELECT contract_name, subject_id, observed_value, expected_reason FROM checks ORDER BY contract_name;
