SET search_path TO bip_pim_024;
WITH active_bookings AS (SELECT seller_id,count(*) FILTER (WHERE booking_state IN ('booked','completed')) active_count,count(*) FILTER (WHERE booking_state='cancelled') cancelled_count FROM bookings GROUP BY seller_id), capacity AS (SELECT s.seller_id,s.display_name,c.capacity_slots,COALESCE(a.active_count,0) active_count,COALESCE(a.cancelled_count,0) cancelled_count,c.capacity_slots-COALESCE(a.active_count,0) remaining FROM sellers s JOIN seller_capacity_windows c ON c.seller_id=s.seller_id LEFT JOIN active_bookings a ON a.seller_id=s.seller_id), pressure AS (SELECT supply.category,supply.location,supply.supply_count,demand.demand_count,demand.demand_count-supply.supply_count pressure FROM local_supply_snapshots supply JOIN local_demand_snapshots demand USING (category,location) WHERE supply.category='cleaning' AND supply.location='North'), checks AS (
SELECT 'pending_offer_not_booking' contract_name,'offer:'||offer_id subject_id,CASE WHEN NOT EXISTS (SELECT 1 FROM bookings b WHERE b.offer_id=o.offer_id) THEN 'not_booking' ELSE 'booking' END observed_value,'Pending offer 301 is not a booking' expected_reason FROM offers o WHERE offer_state='pending'
UNION ALL SELECT 'accepted_offer_booking','offer:'||offer_id,'booking:'||(SELECT booking_id FROM bookings b WHERE b.offer_id=o.offer_id),'Accepted offer 302 creates or links booking 401' FROM offers o WHERE offer_id=302
UNION ALL SELECT 'cancelled_booking_releases_capacity','booking:'||booking_id,booking_state,'Cancelled booking 402 releases capacity' FROM bookings WHERE booking_id=402
UNION ALL SELECT 'completed_booking_consumed','booking:'||booking_id,booking_state,'Completed booking 401 remains historical consumed capacity' FROM bookings WHERE booking_id=401
UNION ALL SELECT 'overbooking_prevented','seller:'||display_name,CASE WHEN remaining>=0 THEN 'prevented' ELSE 'overbooked' END,'Capacity remaining cannot go negative for NorthClean' FROM capacity WHERE display_name='NorthClean'
UNION ALL SELECT 'local_supply_count',category||':'||location,supply_count::text,'Local supply count comes from supply snapshot' FROM pressure
UNION ALL SELECT 'demand_pressure',category||':'||location,pressure::text,'Demand pressure is demand minus supply' FROM pressure
UNION ALL SELECT 'supply_demand_treatment',category||':'||location,CASE WHEN pressure>=3 THEN 'boost' ELSE 'allow' END,'High demand and low supply boosts available listings' FROM pressure
UNION ALL SELECT 'availability_debug_trace','seller:NorthClean','capacity='||capacity_slots||'|active='||active_count||'|cancelled='||cancelled_count||'|remaining='||remaining,'Trace explains capacity, cancellation, and availability treatment' FROM capacity WHERE display_name='NorthClean') SELECT contract_name,subject_id,observed_value,expected_reason FROM checks ORDER BY contract_name;
