SET search_path TO bip_pim_032;
CREATE TABLE users(user_id int PRIMARY KEY, display_name text NOT NULL);
CREATE TABLE communities(community_id int PRIMARY KEY, community_name text NOT NULL, visibility text NOT NULL CHECK (visibility IN ('public','private','invite_only')));
CREATE TABLE community_memberships(membership_id int PRIMARY KEY, community_id int NOT NULL REFERENCES communities(community_id), user_id int NOT NULL REFERENCES users(user_id), member_state text NOT NULL CHECK (member_state IN ('active','pending','left','removed','banned')), source_kind text NOT NULL, source_id int);
CREATE TABLE community_join_requests(request_id int PRIMARY KEY, community_id int NOT NULL REFERENCES communities(community_id), requester_user_id int NOT NULL REFERENCES users(user_id), request_state text NOT NULL CHECK (request_state IN ('pending','approved','rejected','cancelled')), decided_by_user_id int REFERENCES users(user_id), decided_at date);
CREATE TABLE community_invites(invite_id int PRIMARY KEY, community_id int NOT NULL REFERENCES communities(community_id), invited_user_id int NOT NULL REFERENCES users(user_id), invited_by_user_id int NOT NULL REFERENCES users(user_id), invite_state text NOT NULL CHECK (invite_state IN ('sent','accepted','expired','revoked')), expires_at date NOT NULL, accepted_at date);
CREATE TABLE community_bans(ban_id int PRIMARY KEY, community_id int NOT NULL REFERENCES communities(community_id), user_id int NOT NULL REFERENCES users(user_id), banned_by_user_id int NOT NULL REFERENCES users(user_id), reason text NOT NULL);
CREATE TABLE community_request_audit(audit_id int PRIMARY KEY, community_id int NOT NULL REFERENCES communities(community_id), request_id int REFERENCES community_join_requests(request_id), invite_id int REFERENCES community_invites(invite_id), actor_user_id int NOT NULL REFERENCES users(user_id), decision text NOT NULL CHECK (decision IN ('approve','reject','accept_invite','expire_invite','ban_suppressed')), created_at date NOT NULL);

