SET search_path TO bip_pim_032;
WITH active_access AS (SELECT * FROM community_memberships m WHERE m.member_state='active' AND NOT EXISTS(SELECT 1 FROM community_bans b WHERE b.community_id=m.community_id AND b.user_id=m.user_id)), valid_invites AS (SELECT * FROM community_invites WHERE invite_state='accepted' AND expires_at >= DATE '2026-04-01'), audit_trace AS (SELECT * FROM community_request_audit WHERE community_id=101), checks AS (
SELECT 'pending_request_not_member' contract_name,'request:'||request_id subject_id,(NOT EXISTS(SELECT 1 FROM active_access a WHERE a.community_id=r.community_id AND a.user_id=r.requester_user_id))::text observed_value,'Ada request 2001 is pending and has no active membership' expected_reason FROM community_join_requests r WHERE request_id=2001
UNION ALL SELECT 'approved_request_member','request:'||request_id,(EXISTS(SELECT 1 FROM active_access a WHERE a.source_kind='request' AND a.source_id=r.request_id))::text,'Approved request 2002 links to membership 3002' FROM community_join_requests r WHERE request_id=2002
UNION ALL SELECT 'rejected_request_hidden','request:'||request_id,(NOT EXISTS(SELECT 1 FROM active_access a WHERE a.community_id=r.community_id AND a.user_id=r.requester_user_id))::text,'Rejected request 2003 grants no access' FROM community_join_requests r WHERE request_id=2003
UNION ALL SELECT 'valid_invite_membership','invite:4006',(EXISTS(SELECT 1 FROM valid_invites i JOIN active_access a ON a.source_kind='invite' AND a.source_id=i.invite_id WHERE i.invite_id=4006))::text,'Accepted unexpired invite 4006 links to active membership 3006'
UNION ALL SELECT 'expired_invite_denied','invite:4004',(NOT EXISTS(SELECT 1 FROM valid_invites i JOIN active_access a ON a.source_kind='invite' AND a.source_id=i.invite_id WHERE i.invite_id=4004))::text,'Invite 4004 must be accepted and unexpired before access'
UNION ALL SELECT 'banned_invite_denied','invite:4005',(NOT EXISTS(SELECT 1 FROM active_access WHERE source_kind='invite' AND source_id=4005))::text,'Eli ban 5005 suppresses accepted invite 4005'
UNION ALL SELECT 'request_audit_trace','community:101',string_agg(COALESCE('request:'||request_id,'invite:'||invite_id)||':'||decision,'|' ORDER BY audit_id),'Audit rows link request or invite to decision actor'
FROM audit_trace
UNION ALL SELECT 'private_access_contract','community:101',string_agg(user_id::text,'|' ORDER BY user_id),'Only active non-banned memberships can view Private Foundry' FROM active_access WHERE community_id=101)
SELECT contract_name,subject_id,observed_value,expected_reason FROM checks ORDER BY contract_name;
