SET search_path TO bip_pim_029;
WITH visible_messages AS (SELECT m.* FROM messages m JOIN conversation_participants p ON p.conversation_id=m.conversation_id AND p.user_id=1 JOIN conversation_user_settings s ON s.conversation_id=m.conversation_id AND s.user_id=1 WHERE NOT s.archived AND NOT EXISTS(SELECT 1 FROM block_edges b WHERE b.blocker_user_id=1 AND b.blocked_user_id=m.sender_user_id)), inbox AS (SELECT vm.conversation_id,max(vm.sent_rank) latest_rank,max(vm.message_id) FILTER (WHERE vm.sent_rank=(SELECT max(v2.sent_rank) FROM visible_messages v2 WHERE v2.conversation_id=vm.conversation_id)) tie_message FROM visible_messages vm GROUP BY vm.conversation_id), unread AS (SELECT p.conversation_id,count(m.*) unread_count FROM conversation_participants p JOIN messages m ON m.conversation_id=p.conversation_id LEFT JOIN message_read_receipts r ON r.conversation_id=p.conversation_id AND r.user_id=p.user_id WHERE p.user_id=1 AND m.sender_user_id<>1 AND m.message_seq>COALESCE(r.latest_read_seq,0) AND NOT EXISTS(SELECT 1 FROM block_edges b WHERE b.blocker_user_id=1 AND b.blocked_user_id=m.sender_user_id) GROUP BY p.conversation_id), checks AS (
SELECT 'inbox_order' contract_name,'user:Ada' subject_id,string_agg(conversation_id::text,'>' ORDER BY latest_rank DESC, conversation_id DESC) observed_value,'Inbox orders by latest visible message with deterministic tie-breaker' expected_reason FROM inbox
UNION ALL SELECT 'deterministic_tie_breaker','user:Ada',string_agg(conversation_id::text,'>' ORDER BY latest_rank DESC, conversation_id DESC),'Conversation id breaks equal latest_rank ties' FROM inbox WHERE latest_rank=60
UNION ALL SELECT 'muted_suppresses_notification','conversation:101',CASE WHEN s.muted THEN 'no_push' ELSE 'push' END,'Muted conversation remains in inbox but suppresses notification flag' FROM conversation_user_settings s WHERE s.conversation_id=101 AND s.user_id=1
UNION ALL SELECT 'archived_hidden_from_default','conversation:103',(NOT EXISTS(SELECT 1 FROM inbox WHERE conversation_id=103))::text,'Archived conversation 103 is hidden from default inbox'
UNION ALL SELECT 'blocked_sender_suppressed','message:1003',(NOT EXISTS(SELECT 1 FROM visible_messages WHERE message_id=1003))::text,'Blocked sender Cy message is suppressed for Ada'
UNION ALL SELECT 'message_report_review_candidate','message:1004',(EXISTS(SELECT 1 FROM message_reports r JOIN review_queue_items q USING(message_id) WHERE r.message_id=1004))::text,'Report 7001 creates review queue item 8001'
UNION ALL SELECT 'unread_badge','conversation:104',COALESCE((SELECT unread_count::text FROM unread WHERE conversation_id=104),'0'),'Unread badge is derived per user from read receipt and visible messages'
UNION ALL SELECT 'inbox_debug_trace','user:Ada',string_agg(i.conversation_id||':rank='||latest_rank||':unread='||COALESCE(u.unread_count,0),';' ORDER BY latest_rank DESC, i.conversation_id DESC),'Trace explains order, unread, archive, block, and mute handling' FROM inbox i LEFT JOIN unread u USING(conversation_id))
SELECT contract_name,subject_id,observed_value,expected_reason FROM checks ORDER BY contract_name;
