SET search_path TO bip_pim_033;
WITH active_members AS (SELECT * FROM community_memberships WHERE member_state='active'), removed_posts AS (SELECT post_id FROM community_post_moderation_actions WHERE action_type IN ('hide','remove')), visible_posts AS (SELECT viewer.user_id viewer_user_id,p.* FROM active_members viewer JOIN community_posts p ON p.community_id=viewer.community_id JOIN community_channels ch ON ch.channel_id=p.channel_id WHERE p.post_state='active' AND NOT EXISTS(SELECT 1 FROM removed_posts rp WHERE rp.post_id=p.post_id) AND (ch.channel_visibility='public' OR EXISTS(SELECT 1 FROM channel_memberships cm WHERE cm.channel_id=ch.channel_id AND cm.user_id=viewer.user_id AND cm.channel_member_state='active'))), checks AS (
SELECT 'public_channel_post_visible' contract_name,'user:1/post:1001' subject_id,(EXISTS(SELECT 1 FROM visible_posts WHERE viewer_user_id=1 AND post_id=1001))::text observed_value,'Ada active membership 3001 can see public channel post 1001' expected_reason
UNION ALL SELECT 'private_channel_member_visible','user:2/post:1002',(EXISTS(SELECT 1 FROM visible_posts WHERE viewer_user_id=2 AND post_id=1002))::text,'Ben channel membership 5002 can see private channel post 1002'
UNION ALL SELECT 'private_channel_non_member_hidden','user:3/post:1002',(NOT EXISTS(SELECT 1 FROM visible_posts WHERE viewer_user_id=3 AND post_id=1002))::text,'Cy active community member lacks channel_memberships row for channel 202'
UNION ALL SELECT 'removed_member_hidden','user:4',(NOT EXISTS(SELECT 1 FROM visible_posts WHERE viewer_user_id=4))::text,'Diya membership 3004 is removed and sees no community posts'
UNION ALL SELECT 'deleted_post_hidden','post:1004',(NOT EXISTS(SELECT 1 FROM visible_posts WHERE post_id=1004))::text,'Deleted post 1004 is suppressed'
UNION ALL SELECT 'pinned_post_contract','community:101',string_agg(post_id::text,'|' ORDER BY created_rank),'Pinned visible posts derive from community_posts.is_pinned' FROM visible_posts WHERE viewer_user_id=1 AND is_pinned
UNION ALL SELECT 'thread_reply_contract','thread:6001',(SELECT parent_post_id||'->'||reply_post_id FROM community_threads WHERE thread_id=6001),'Reply post 1003 stays attached to parent post 1001'
UNION ALL SELECT 'channel_visibility_trace','community:101',string_agg(viewer_user_id||':'||post_id,'|' ORDER BY viewer_user_id,post_id),'Trace combines member state, channel visibility, deletion, and moderation state' FROM visible_posts)
SELECT contract_name,subject_id,observed_value,expected_reason FROM checks ORDER BY contract_name;
